topics:
  -
    topic: /locobot/battery_state
    type: sensor_msgs/msg/BatteryState
  -
    topic: /locobot/cmd_audio
    type: irobot_create_msgs/msg/AudioNoteVector
  -
    topic: /locobot/cmd_lightring
    type: irobot_create_msgs/msg/LightringLeds
  -
    topic: /locobot/cmd_vel
    type: geometry_msgs/msg/Twist
  -
    topic: /locobot/dock
    type: irobot_create_msgs/msg/Dock
  -
    topic: /locobot/hazard_detection
    type: irobot_create_msgs/msg/HazardDetectionVector
  -
    topic: /locobot/imu
    type: sensor_msgs/msg/Imu
  -
    topic: /locobot/interface_buttons
    type: irobot_create_msgs/msg/InterfaceButtons
  -
    topic: /locobot/ir_intensity
    type: irobot_create_msgs/msg/IrIntensityVector
  -
    topic: /locobot/ir_opcode
    type: irobot_create_msgs/msg/IrOpcode
  -
    topic: /locobot/kidnap_status
    type: irobot_create_msgs/msg/KidnapStatus
  -
    topic: /locobot/mouse
    type: irobot_create_msgs/msg/Mouse
  -
    topic: /locobot/odom
    type: nav_msgs/msg/Odometry
  -
    topic: /locobot/rosout
    type: rcl_interfaces/msg/Log
  -
    topic: /locobot/slip_status
    type: irobot_create_msgs/msg/SlipStatus
  -
    topic: /locobot/stop_status
    type: irobot_create_msgs/msg/StopStatus
  -
    topic: /locobot/tf
    type: tf2_msgs/msg/TFMessage
  -
    topic: /locobot/tf_static
    type: tf2_msgs/msg/TFMessage
  -
    topic: /locobot/wheel_status
    type: irobot_create_msgs/msg/WheelStatus
  -
    topic: /locobot/wheel_ticks
    type: irobot_create_msgs/msg/WheelTicks
  -
    topic: /locobot/wheel_vels
    type: irobot_create_msgs/msg/WheelVels
